name: helics-environment
channels:
  - conda-forge
  - gmlc-tdc
dependencies:
  - numpy=1.16.4
  - scipy=1.3.0
  - matplotlib=3.1.1
  - pandas=0.25.0
  - helics=2.2.0
  - ipywidgets=7.5.1
  - nb_conda=2.2.1
  - rise=5.5.1
  - pip=19.2.1
  - pip:
    - OpenDSSDirect.py==0.3.7
    - PYPOWER==5.1.4
    - jupyter-contrib-nbextensions==0.5.1
